# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'etternuino.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_self(object):
    def setupUi(self):
        self.setObjectName("self")
        self.resize(254, 463)
        self.setWindowTitle("Etternuino")
        self.main_widget = QtWidgets.QWidget(self)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lane_group = QtWidgets.QWidget(self.main_widget)
        self.lane_group.setObjectName("lane_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.lane_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lane_0 = QtWidgets.QFrame(self.lane_group)
        self.lane_0.setMinimumSize(QtCore.QSize(50, 50))
        self.lane_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lane_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lane_0.setObjectName("lane_0")
        self.horizontalLayout.addWidget(self.lane_0)
        self.lane_1 = QtWidgets.QFrame(self.lane_group)
        self.lane_1.setMinimumSize(QtCore.QSize(50, 50))
        self.lane_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lane_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lane_1.setObjectName("lane_1")
        self.horizontalLayout.addWidget(self.lane_1)
        self.lane_2 = QtWidgets.QFrame(self.lane_group)
        self.lane_2.setMinimumSize(QtCore.QSize(50, 50))
        self.lane_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lane_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lane_2.setObjectName("lane_2")
        self.horizontalLayout.addWidget(self.lane_2)
        self.lane_3 = QtWidgets.QFrame(self.lane_group)
        self.lane_3.setMinimumSize(QtCore.QSize(50, 50))
        self.lane_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lane_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lane_3.setObjectName("lane_3")
        self.horizontalLayout.addWidget(self.lane_3)
        self.verticalLayout_2.addWidget(self.lane_group)
        self.checkbox_group = QtWidgets.QWidget(self.main_widget)
        self.checkbox_group.setObjectName("checkbox_group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.checkbox_group)
        self.verticalLayout.setObjectName("verticalLayout")
        self.play_music_checkbox = QtWidgets.QCheckBox(self.checkbox_group)
        self.play_music_checkbox.setChecked(True)
        self.play_music_checkbox.setObjectName("play_music_checkbox")
        self.verticalLayout.addWidget(self.play_music_checkbox)
        self.signal_arduino_checkbox = QtWidgets.QCheckBox(self.checkbox_group)
        self.signal_arduino_checkbox.setChecked(True)
        self.signal_arduino_checkbox.setObjectName("signal_arduino_checkbox")
        self.verticalLayout.addWidget(self.signal_arduino_checkbox)
        self.add_claps_checkbox = QtWidgets.QCheckBox(self.checkbox_group)
        self.add_claps_checkbox.setObjectName("add_claps_checkbox")
        self.verticalLayout.addWidget(self.add_claps_checkbox)
        self.verticalLayout_2.addWidget(self.checkbox_group)
        self.play_group = QtWidgets.QWidget(self.main_widget)
        self.play_group.setObjectName("play_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.play_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play_file_btn = QtWidgets.QPushButton(self.play_group)
        self.play_file_btn.setFlat(False)
        self.play_file_btn.setObjectName("play_file_btn")
        self.horizontalLayout_2.addWidget(self.play_file_btn)
        self.verticalLayout_2.addWidget(self.play_group)
        self.control_group = QtWidgets.QWidget(self.main_widget)
        self.control_group.setObjectName("control_group")
        self.play_active_group = QtWidgets.QHBoxLayout(self.control_group)
        self.play_active_group.setObjectName("play_active_group")
        self.pause_stop_group = QtWidgets.QWidget(self.control_group)
        self.pause_stop_group.setEnabled(True)
        self.pause_stop_group.setObjectName("pause_stop_group")
        self.ctrl_button_group = QtWidgets.QVBoxLayout(self.pause_stop_group)
        self.ctrl_button_group.setObjectName("ctrl_button_group")
        self.pause_btn = QtWidgets.QPushButton(self.pause_stop_group)
        self.pause_btn.setObjectName("pause_btn")
        self.ctrl_button_group.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.pause_stop_group)
        self.stop_btn.setObjectName("stop_btn")
        self.ctrl_button_group.addWidget(self.stop_btn)
        self.play_active_group.addWidget(self.pause_stop_group)
        self.label_3 = QtWidgets.QLabel(self.control_group)
        self.label_3.setObjectName("label_3")
        self.play_active_group.addWidget(self.label_3)
        self.progress_slider = QtWidgets.QSlider(self.control_group)
        self.progress_slider.setMaximum(0)
        self.progress_slider.setSingleStep(4410)
        self.progress_slider.setPageStep(44100)
        self.progress_slider.setOrientation(QtCore.Qt.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.play_active_group.addWidget(self.progress_slider)
        self.verticalLayout_2.addWidget(self.control_group)
        self.widget = QtWidgets.QWidget(self.main_widget)
        self.widget.setObjectName("widget")
        self.control_sliders_group = QtWidgets.QHBoxLayout(self.widget)
        self.control_sliders_group.setObjectName("control_sliders_group")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.control_sliders_group.addWidget(self.label)
        self.blink_duration_slider = QtWidgets.QSlider(self.widget)
        self.blink_duration_slider.setMaximum(150)
        self.blink_duration_slider.setPageStep(10)
        self.blink_duration_slider.setProperty("value", 50)
        self.blink_duration_slider.setTracking(True)
        self.blink_duration_slider.setOrientation(QtCore.Qt.Vertical)
        self.blink_duration_slider.setInvertedAppearance(False)
        self.blink_duration_slider.setInvertedControls(False)
        self.blink_duration_slider.setObjectName("blink_duration_slider")
        self.control_sliders_group.addWidget(self.blink_duration_slider)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.control_sliders_group.addWidget(self.label_2)
        self.microblink_duration_slider = QtWidgets.QSlider(self.widget)
        self.microblink_duration_slider.setMaximum(50)
        self.microblink_duration_slider.setProperty("value", 10)
        self.microblink_duration_slider.setOrientation(QtCore.Qt.Vertical)
        self.microblink_duration_slider.setObjectName("microblink_duration_slider")
        self.control_sliders_group.addWidget(self.microblink_duration_slider)
        self.verticalLayout_2.addWidget(self.widget)
        self.setCentralWidget(self.main_widget)

        self.retranslateUi(self)
        self.play_file_btn.clicked.connect(self.play_file)
        self.pause_btn.clicked.connect(self.pause)
        self.stop_btn.clicked.connect(self.stop)
        self.play_music_checkbox.toggled['bool'].connect(self.play_music)
        self.signal_arduino_checkbox.toggled['bool'].connect(self.signal_arduino)
        self.add_claps_checkbox.toggled['bool'].connect(self.add_claps)
        self.blink_duration_slider.sliderMoved['int'].connect(self.change_blink_duration)
        self.microblink_duration_slider.sliderMoved['int'].connect(self.change_microblink_duration)
        self.progress_slider.sliderMoved['int'].connect(self.change_current_time)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.play_music_checkbox.setText(_translate("self", "Play music"))
        self.signal_arduino_checkbox.setText(_translate("self", "Signal Arduino"))
        self.add_claps_checkbox.setText(_translate("self", "Add claps"))
        self.play_file_btn.setText(_translate("self", "Play file"))
        self.pause_btn.setText(_translate("self", "Pause"))
        self.stop_btn.setText(_translate("self", "Stop"))
        self.label_3.setText(_translate("self", "Progress:"))
        self.label.setText(_translate("self", "Blink duration:"))
        self.label_2.setText(_translate("self", "Microblink duration"))
